import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Inknut_Antiqua } from 'next/font/google';
import { Roboto } from 'next/font/google';
import "./globals.css";

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '700'], // kamu bisa tambahkan '300', '500', '900' sesuai kebutuhan
});

const inknut = Inknut_Antiqua({
  subsets: ['latin'],
  weight: ['400', '700'], // pilih sesuai kebutuhan
});


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "My Personal Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
   
      <head>
        <link
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
